/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffe089",
        "surface-variant": "#e2e2e2",
        "secondary-fixed": "#e9e0e1",
        "on-primary-container": "#6f5800",
        "on-surface-variant": "#4e4632",
        "status-success": "#10b981",
        "on-tertiary-fixed-variant": "#474647",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#cdc4c5",
        "primary-container": "#ffcd00",
        "status-error": "#ef4444",
        surface: "#f8fafc",
        tertiary: "#5f5e5e",
        "surface-navigation": "#2f3131",
        "on-secondary": "#ffffff",
        "on-surface": "#0f172a",
        "tertiary-container": "#d5d2d2",
        "on-tertiary-container": "#5b5a5a",
        "inverse-primary": "#f0c100",
        "on-tertiary": "#ffffff",
        secondary: "#64748b",
        "on-error": "#ffffff",
        error: "#ef4444",
        background: "#f8fafc",
        "on-primary-fixed": "#241a00",
        "cat-charcoal": "#181a1d",
        "cat-charcoal-light": "#22262b",
        "tertiary-fixed": "#e5e2e1",
        "surface-container-low": "#f1f5f9",
        "on-secondary-fixed": "#1e1b1c",
        "surface-bright": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-highest": "#e2e8f0",
        "surface-dim": "#cbd5e1",
        "on-background": "#0f172a",
        "secondary-container": "#e2e8f0",
        "on-tertiary-fixed": "#1c1b1c",
        "on-secondary-container": "#475569",
        primary: "#d97706",
        "outline-variant": "#e2e8f0",
        "on-secondary-fixed-variant": "#4b4546",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f8fafc",
        "on-primary-fixed-variant": "#574500",
        "surface-tint": "#d97706",
        outline: "#94a3b8",
        "status-warning": "#f59e0b",
        "tertiary-fixed-dim": "#c8c6c6",
        "cat-yellow": "#ffcd00",
        "cat-yellow-hover": "#f5c400",
        "surface-container-high": "#e2e8f0",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#f0c100",
      },
      borderRadius: {
        none: "0px",
        sm: "0.375rem",   /* 6px */
        DEFAULT: "0.5rem",/* 8px */
        md: "0.5rem",     /* 8px */
        lg: "0.75rem",    /* 12px */
        xl: "1rem",       /* 16px */
        "2xl": "1.25rem", /* 20px */
        "3xl": "1.5rem",  /* 24px */
        full: "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgba(0, 0, 0, 0.04)",
        sm: "0 1px 3px 0 rgba(0, 0, 0, 0.06), 0 1px 2px -1px rgba(0, 0, 0, 0.04)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -2px rgba(0, 0, 0, 0.04)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.03)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.04)",
        modal: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      },
      spacing: {
        "margin-mobile": "16px",
        "table-cell-padding": "14px 18px",
        "margin-desktop": "24px",
        gutter: "16px",
        base: "4px",
        "card-padding": "20px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

